// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD52fdgMPCTzY-XfN3rVE0zlBxRbs409eU',
    appId: '1:206536007011:web:4f3f1402d580d57047c756',
    messagingSenderId: '206536007011',
    projectId: 'attendance-routine-app',
    authDomain: 'attendance-routine-app.firebaseapp.com',
    storageBucket: 'attendance-routine-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKMylryu3_HCZzBQmfSQdiXbynbeTJF48',
    appId: '1:206536007011:android:9dfbf4fca99fb76647c756',
    messagingSenderId: '206536007011',
    projectId: 'attendance-routine-app',
    storageBucket: 'attendance-routine-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF_J-Mpb2QI1rGNlU4CjPPp_voN9jZ3s4',
    appId: '1:206536007011:ios:3bba974d0b3d686f47c756',
    messagingSenderId: '206536007011',
    projectId: 'attendance-routine-app',
    storageBucket: 'attendance-routine-app.firebasestorage.app',
    iosBundleId: 'com.example.attendanceRoutineApp',
  );
}
